name: fcm_sending
description: "Fcm Sending is a simple Flutter package that helps developers send customized notifications with ease. It automatically converts the notification message body into a Dart model, making it user-friendly and reducing confusion when handling notification data. Perfect for apps that need to integrate push notifications without the hassle of complex payload management."
version: 0.0.4
repository: https://github.com/elbeekk/fcm_sending
homepage:
environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth: any
  shared_preferences: any
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
